"""initial migration

Revision ID: 2762c175a875
Revises: 
Create Date: 2026-04-05 23:53:43.563145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2762c175a875'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_bots',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(length=255), nullable=False),
    sa.Column('bot_type', sa.String(length=50), nullable=True),
    sa.Column('bot_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_index(op.f('ix_ai_bots_bot_id'), 'ai_bots', ['bot_id'], unique=False)
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicants_email'), 'applicants', ['email'], unique=True)
    op.create_index(op.f('ix_applicants_id'), 'applicants', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.create_table('ai_bot_applicants',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['ai_bots.bot_id'], ),
    sa.PrimaryKeyConstraint('bot_id', 'applicant_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_range', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['ai_bots.bot_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    op.create_table('job_applicants',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'applicant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applicants')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('ai_bot_applicants')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_applicants_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_email'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_index(op.f('ix_ai_bots_bot_id'), table_name='ai_bots')
    op.drop_table('ai_bots')
    # ### end Alembic commands ###
