"""remove conversation_metadata column from chatbot_message

Revision ID: fa81e4cb8827
Revises: 591f61c5ee52
Create Date: 2026-05-05 19:26:03.254543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa81e4cb8827'
down_revision: Union[str, Sequence[str], None] = '591f61c5ee52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'conversation_metadata')
    op.drop_index(op.f('idx_job_embedding'), table_name='jobs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_job_embedding'), 'jobs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('chat_messages', sa.Column('conversation_metadata', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
